import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        outline: "#777777",
        "primary-fixed": "#005ac2",
        error: "#ba1a1a",
        "surface-tint": "#005ac2",
        "on-error": "#ffffff",
        primary: "#000000",
        "inverse-primary": "#adc6ff",
        "on-tertiary-fixed-variant": "#e2e2e2",
        "on-secondary-fixed-variant": "#662900",
        "surface-container-low": "#f2f3ff",
        "on-secondary-fixed": "#341100",
        "on-background": "#131b2e",
        "outline-variant": "#c6c6c6",
        "tertiary-fixed": "#5e5e5e",
        "on-primary-fixed": "#ffffff",
        "inverse-surface": "#283044",
        "on-tertiary-fixed": "#ffffff",
        "surface-dim": "#d2d9f4",
        "on-secondary": "#ffffff",
        "primary-container": "#00397f",
        secondary: "#9d4300",
        "tertiary-container": "#747474",
        "inverse-on-surface": "#eef0ff",
        "surface-container-lowest": "#ffffff",
        "on-primary-container": "#ffffff",
        "on-tertiary": "#e2e2e2",
        "on-tertiary-container": "#ffffff",
        "secondary-fixed": "#ffb690",
        "on-surface": "#131b2e",
        "secondary-fixed-dim": "#ff8d4b",
        "on-error-container": "#410002",
        "surface-container": "#eaedff",
        "surface-bright": "#faf8ff",
        "on-surface-variant": "#474747",
        "surface-variant": "#dae2fd",
        "on-secondary-container": "#341100",
        tertiary: "#3b3b3b",
        "secondary-container": "#ffc9ae",
        "error-container": "#ffdad6",
        "surface-container-high": "#e2e7ff",
        background: "#faf8ff",
        "on-primary": "#d8e2ff",
        "primary-fixed-dim": "#004395",
        "tertiary-fixed-dim": "#474747",
        "on-primary-fixed-variant": "#d8e2ff",
        surface: "#faf8ff",
        "surface-container-highest": "#dae2fd",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      fontFamily: {
        headline: ["Inter", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [require("@tailwindcss/forms")],
};

export default config;
